[project]
name = 'tokenvote'
description = 'A decentralized voting system for token holders on Stacks'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.governance-token]
path = 'contracts/GovernanceToken.clar'
clarity_version = 2
epoch = 2.4

[contracts.tokenvote]
path = 'contracts/TokenVote.clar'
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2
